> #### Basics of Python

- Variable
- Operator
- Type Casting

In [1]:
a=10

In [2]:
a

10

In [3]:
a+23

33

In [4]:
type(a)

int

In [5]:
s="Sandeep"

In [6]:
type(s)

str

In [154]:
S="sandeep"

In [155]:
type(S)

str

In [156]:
id(s)

1712106813936

In [157]:
add1=id(S)

In [13]:
n=23.53

In [14]:
type(n)

float

In [18]:
# invalid Variabel Name
s% = "ss"

SyntaxError: invalid syntax (2410767829.py, line 1)

In [19]:
a=True

In [20]:
type(a)

bool

In [21]:
id(a)

140709861709928

In [22]:
True + False

1

In [23]:
False + False

0

In [24]:
True + True

2

In [25]:
c=1+3j

In [26]:
type(c)

complex

In [27]:
c.imag

3.0

In [28]:
c.real

1.0

In [32]:
d=complex(3,-6)

In [33]:
d

(3-6j)

In [34]:
f=23

In [35]:
f+3

26

In [36]:
g="ad"

In [37]:
#Invalid Operation
g+3

TypeError: can only concatenate str (not "int") to str

> #### Slicing

In [38]:
s="Sandeep"

In [39]:
s[2]

'n'

In [40]:
s[2:5]

'nde'

In [41]:
s[5:2]

''

In [42]:
s[5:2:-1]

'eed'

In [43]:
s[2:-3]

'nd'

In [44]:
s[-2:-6]

''

In [45]:
s[-2:-6:-1]

'eedn'

In [87]:
s="This is my very first programming class's"

In [49]:
type(s)

str

In [52]:
s[20:23]

't p'

In [53]:
s[2:34]

'is is my very first programming '

In [54]:
s[2:7]

'is is'

In [55]:
s[4:26:2]

' sm eyfrtpo'

In [56]:
s="Python"

In [57]:
s[::-1]

'nohtyP'

In [58]:
s[:-3]

'Pyt'

In [59]:
s[-3:]

'hon'

In [60]:
s[-7:-1:1]

'Pytho'

In [62]:
s[-7:0:1]

''

In [63]:
s[8:0:-1]

'nohty'

In [64]:
s[8:0:1]

''

In [65]:
s[0:8]

'Python'

In [67]:
s[8:3:-1]

'no'

In [69]:
s.count("is")

2

In [72]:
s.split(" ")

['This', 'is', 'my', 'very', 'first', 'programming', "class's"]

In [71]:
type(s)

str

In [74]:
s.capitalize()

"This is my very first programming class's"

In [88]:
s.upper()

"THIS IS MY VERY FIRST PROGRAMMING CLASS'S"

In [89]:
s

"This is my very first programming class's"

In [78]:
s1

"THIS IS MY VERY FIRST PROGRAMMING CLASS'S"

In [79]:
s.title()

"This Is My Very First Programming Class'S"

In [80]:
s.capitalize()

"This is my very first programming class's"

In [81]:
s.swapcase()

"tHIS IS MY VERY FIRST PROGRAMMING CLASS'S"

In [82]:
s1.swapcase()

"this is my very first programming class's"

In [91]:
"".join(reversed(s))

"s'ssalc gnimmargorp tsrif yrev ym si sihT"

In [94]:
s ="  H E L    L    O  "

In [93]:
s.strip()

'H E L    L    o'

In [95]:
"a".join("Sandeep")

'Saaanadaeaeap'

In [97]:
s="Sandeep"

In [99]:
s.center(20,"*")

'******Sandeep*******'

In [100]:
a="  "

In [101]:
a.islower()

False

In [102]:
a.isupper()

False

In [103]:
a.isprintable()

True

In [104]:
a

'  '

In [105]:
a.istitle()

False

In [113]:
b="1212324"

In [107]:
b.isnumeric()

True

In [108]:
b.isalpha()

False

In [109]:
b.isdigit()

True

In [114]:
b.isspace()

False

In [115]:
s="Sandeep"

In [116]:
s.isspace()

False

In [117]:
s="S    and  eeep"

In [118]:
s.isspace()

False

In [140]:
s="Sandy123    "

In [141]:
s.isalnum()

False

In [131]:
s.format()

'Sandy123'

In [142]:
s="2334325235"

In [143]:
s.isnumeric()

True

In [144]:
s="23343 25235"

In [145]:
s.isnumeric()

False

In [151]:
add=id(s)

In [158]:
var2 = [x for x in globals().values() if id(x)==add1]

In [159]:
var2

['sandeep']

In [163]:
s="my\tname\tis\tSandeep"

In [164]:
s

'my\tname\tis\tSandeep'

In [165]:
s.expandtabs()

'my      name    is      Sandeep'

> #### List, Tuple, Set and Dictionary

In [166]:
l=[1,2,3,4,5,"Sandeep",213.13,True]

In [167]:
l[2]

3

In [168]:
l[-1]

True

In [169]:
len(l)

8

In [170]:
l[::-1]

[True, 213.13, 'Sandeep', 5, 4, 3, 2, 1]

In [171]:
l+l

[1,
 2,
 3,
 4,
 5,
 'Sandeep',
 213.13,
 True,
 1,
 2,
 3,
 4,
 5,
 'Sandeep',
 213.13,
 True]

In [172]:
l

[1, 2, 3, 4, 5, 'Sandeep', 213.13, True]

In [175]:
["a"]+l

['a', 1, 2, 3, 4, 5, 'Sandeep', 213.13, True]

In [176]:
l

[1, 2, 3, 4, 5, 'Sandeep', 213.13, True]

In [179]:
l=l+["a"]

In [180]:
l

[1, 2, 3, 4, 5, 'Sandeep', 213.13, True, 'a']

In [181]:
2 in l

True

In [182]:
a in l

False

In [183]:
'a' in l

True

In [184]:
max(l)

TypeError: '>' not supported between instances of 'str' and 'int'

In [186]:
l2=[23,28,423,135135,15,1234,132,1235,1325,135]

In [187]:
max(l2)

135135

In [192]:
S=["aaa","AAA","aAa"]

In [193]:
max(S)

'aaa'

In [195]:
min(S)

'AAA'

In [1]:
l=[1,2,3,4,5,6]

In [2]:
l2=[7,8,9]

In [3]:
l+l2

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
l.extend(l2)

In [5]:
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
l.reverse()

In [7]:
l

[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [21]:
l1=[1,2,3]
l2=[3,4,5]
l3=[6,7,8]

In [22]:
l4=[l1,l2,l3]

In [23]:
l4

[[1, 2, 3], [3, 4, 5], [6, 7, 8]]

In [24]:
l4.count(3)

0

In [29]:
l5=[3,4,6,7,3,2,7,8,3,1,4,2,5]

In [30]:
l5.count(3)

3

In [31]:
l5.insert(0,[11,45])

In [32]:
l5

[[11, 45], 3, 4, 6, 7, 3, 2, 7, 8, 3, 1, 4, 2, 5]

In [33]:
l5.pop()

5

In [34]:
l5

[[11, 45], 3, 4, 6, 7, 3, 2, 7, 8, 3, 1, 4, 2]

In [36]:
l5.pop(0)

[11, 45]

In [37]:
l5

[3, 4, 6, 7, 3, 2, 7, 8, 3, 1, 4, 2]

In [38]:
l5.sort()

In [39]:
l5

[1, 2, 2, 3, 3, 3, 4, 4, 6, 7, 7, 8]

In [40]:
l5.remove(0)

ValueError: list.remove(x): x not in list

In [41]:
l5.remove(2)

In [42]:
l5

[1, 2, 3, 3, 3, 4, 4, 6, 7, 7, 8]

In [43]:
# Tuple
t=(2,4,52,5,7,"Sandeep",True,23.54)

In [44]:
t

(2, 4, 52, 5, 7, 'Sandeep', True, 23.54)

In [46]:
t[3]

5

In [47]:
t[0:]

(2, 4, 52, 5, 7, 'Sandeep', True, 23.54)

In [48]:
t[:4]

(2, 4, 52, 5)

In [49]:
t[2]="sdfmsf"

TypeError: 'tuple' object does not support item assignment

In [50]:
t2=(234,523,2,5,62,621)

In [52]:
t3=t+t2

In [53]:
t3

(2, 4, 52, 5, 7, 'Sandeep', True, 23.54, 234, 523, 2, 5, 62, 621)

In [54]:
t3.count(2)

2

In [57]:
t3.index(234)

8

In [58]:
l=[1,2,3,5,6,7,8,9,9,4,3,2,1,21,4,56,7,8,8]

In [59]:
t=tuple(l)

In [60]:
t

(1, 2, 3, 5, 6, 7, 8, 9, 9, 4, 3, 2, 1, 21, 4, 56, 7, 8, 8)

In [62]:
l2=list(t)

In [63]:
l2

[1, 2, 3, 5, 6, 7, 8, 9, 9, 4, 3, 2, 1, 21, 4, 56, 7, 8, 8]

In [64]:
str(t)

'(1, 2, 3, 5, 6, 7, 8, 9, 9, 4, 3, 2, 1, 21, 4, 56, 7, 8, 8)'

In [65]:
t[4]

6

In [66]:
#Dictionary

d={}

In [67]:
type(d)

dict

In [68]:
d={3}

In [69]:
d

{3}

In [70]:
type(d)

set

In [71]:
d={1:3}

In [72]:
d

{1: 3}

In [73]:
type(d)

dict

In [74]:
d={1:2}

In [75]:
d

{1: 2}

In [80]:
d={1:5,'1':5}

In [81]:
d

{1: 5, '1': 5}

In [82]:
d.keys()

dict_keys([1, '1'])

In [83]:
d1={"Name":"Sandeep","Age":20}

In [84]:
d1.items()

dict_items([('Name', 'Sandeep'), ('Age', 20)])

In [85]:
d2={"Names":{1:"Sandeep",2:"Pintu"}}

In [86]:
d2

{'Names': {1: 'Sandeep', 2: 'Pintu'}}

In [88]:
d2["Names"]

{1: 'Sandeep', 2: 'Pintu'}

In [89]:
d2["Names"][1]

'Sandeep'

In [91]:
"Names" in d2

True

In [95]:
2 in d2.keys() #???

False

In [96]:
d2[1]="xyz"

In [97]:
d2

{'Names': {1: 'Sandeep', 2: 'Pintu'}, 1: 'xyz'}

In [98]:
d+d2

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'

In [99]:
d2.keys()

dict_keys(['Names', 1])

In [100]:
d2.values()

dict_values([{1: 'Sandeep', 2: 'Pintu'}, 'xyz'])

In [101]:
d2.items()

dict_items([('Names', {1: 'Sandeep', 2: 'Pintu'}), (1, 'xyz')])

In [112]:
# Set
s={1,2,4,6,7,8,9,3,0,12,14,1}

In [103]:
s

{1, 2, 3, 4, 6, 7, 8, 9}

In [106]:
s1=s.copy()

In [107]:
s1

{1, 2, 3, 4, 6, 7, 8, 9}

In [113]:
s.difference(s1)

{0, 12, 14}

In [114]:
s

{0, 1, 2, 3, 4, 6, 7, 8, 9, 12, 14}

In [115]:
s.union(s1)

{0, 1, 2, 3, 4, 6, 7, 8, 9, 12, 14}

In [116]:
s.intersection(s1)

{1, 2, 3, 4, 6, 7, 8, 9}

In [117]:
s.issubset(s1)

False

In [118]:
s1.issubset(s)

True

In [119]:
s1.issuperset(s)

False

In [120]:
s.issuperset(s1)

True

In [123]:
s[2]

TypeError: 'set' object is not subscriptable

In [124]:
list(s)

[0, 1, 2, 3, 4, 6, 7, 8, 9, 12, 14]

In [125]:
s

{0, 1, 2, 3, 4, 6, 7, 8, 9, 12, 14}

In [126]:
tuple(s)

(0, 1, 2, 3, 4, 6, 7, 8, 9, 12, 14)

In [138]:
s={1,2,4,5,5,5,5,5,2,2,2,2,4,4,1,5,15,15,15,15,54,15,}

In [139]:
s

{1, 2, 4, 5, 15, 54}

In [140]:
s.add(100)

In [141]:
s

{1, 2, 4, 5, 15, 54, 100}

In [132]:
s.add([1,2,3,5])

TypeError: unhashable type: 'list'

In [144]:
s1={(1,2,34,4),1,2,34,4}

In [145]:
s.remove(34)

KeyError: 34

In [149]:
s1.discard(34)

TypeError: set.discard() takes exactly one argument (2 given)

In [148]:
s1

{(1, 2, 34, 4), 1, 2, 4}

In [151]:
# Question
d={"Name":"Sandeep","Contact_info":12345,"Name":"Rupe"}
d['loc']="Category"
d['Check']=d

print(d['Check'])

{'Name': 'Rupe', 'Contact_info': 12345, 'loc': 'Category', 'Check': {...}}


In [152]:
print(d.keys())

dict_keys(['Name', 'Contact_info', 'loc', 'Check'])


In [153]:
print(d.items())

dict_items([('Name', 'Rupe'), ('Contact_info', 12345), ('loc', 'Category'), ('Check', {'Name': 'Rupe', 'Contact_info': 12345, 'loc': 'Category', 'Check': {...}})])


In [154]:
print(type(d.keys()))

<class 'dict_keys'>


In [158]:
print(type(d.items()))

<class 'dict_items'>


In [159]:
n=[4,5,7,9,2,3,4,5,2,1,9,6,7,8,]

In [160]:
n.pop()

8

In [161]:
n.sort()

In [162]:
n

[1, 2, 2, 3, 4, 4, 5, 5, 6, 7, 7, 9, 9]

In [4]:
# Question
l=[3,4,5,6,7,[23,456,67,8,78,78],(234,6657,6),[345,56,87,8,98,9],{'key1':"python",234:[23,45,656]}]

#1.Try to reverse the list
#l.reverse()
l[::-1]

[{'key1': 'python', 234: [23, 45, 656]},
 [345, 56, 87, 8, 98, 9],
 (234, 6657, 6),
 [23, 456, 67, 8, 78, 78],
 7,
 6,
 5,
 4,
 3]

In [31]:
#2. Try to access 234 out of the list l
#l[6][0]
l1=l[8].keys()
l1

dict_keys(['key1', 234])

In [20]:
#3. try to access 456
l[5][1]

456

In [21]:
#4. Try to extract only a list collection from list 1
l[5]

[23, 456, 67, 8, 78, 78]

In [24]:
#5. Try to extract "python"
l[8]['key1']

'python'

In [27]:
#6. Try to list all the key in dict element available in the list
l1=l[8].keys()

In [28]:
l1

dict_keys(['key1', 234])

>### Conditional Statements 

In [34]:
a=10
if a==10:
    print("The value is",a)
    print("First condition")

The value is 10
First condition


In [35]:
a=10
if a>5:
    pass

In [37]:
a=20
if a<10:
    print("This if condition is True")

In [38]:
a=10
if a==11:
    print("My condition is False")
else:
    print("The value of a is",a)

The value of a is 10


In [41]:
a=10
if a ==12:
    print("Here we comparing 10 with 12")
elif a==11:
    print("Here we competing 10 with 11")
else:
    print("If all block will fail, do this")

If all block will fail, do this


In [42]:
price=500
if price>500:
    print("Maybe I won't be able to buy the jacket")
elif price<500:
    print("I will able to but the Jacket")
elif price==500:
    print("For sure, I will buy the Jacket")
else:
    print("The price is unknown")
    

For sure, I will buy the Jacket


In [43]:
price>500

False

In [44]:
price<500

False

In [45]:
price==500

True

In [48]:
l=[1,2,3,4,5,6]
2 in l

True

In [49]:
if 60 in l:
    print("60 is present in the List l")
else:
    print("60 is not present in the list l")

60 is not present in the list l


In [50]:
60 in l

False

In [51]:
l

[1, 2, 3, 4, 5, 6]

In [53]:
if 10 in l:
    print("Try to do a addition")
elif 2 in l:
    print("Try to do Sub")
elif 3 in l:
    print("Try to do Mul")
if 4 in l:
    print("This is new statement")

Try to do Sub
This is new statement


In [57]:
price=int(input("Enter the Price:"))
if price<500:
    print("I will able to Buy something")
    if price<400:
        print("I will buy the Jacket")
    elif price <300:
        print("I will able to buy a Shirt only")
        if price <200:
            print("I would like to do Something")
    else:
        print("I wont be able to buy anything")
else:
    print("I wont be able to buy something with this price tag")
    if price>500:
        print("The  price is",price)
        

Enter the Price:120
I will able to Buy something
I will buy the Jacket


In [58]:
marks=int(input())
if marks<600:
    print("Second Division")
    if marks<500:
        print("Average Performance")
        if marks<400:
            print("Improvement Needed")
    else:
        print("The performance is not up to the Mark")
else:
    print("You got First Division")

450
Second Division
Average Performance


In [60]:
val = float(input("Enter a float point number:"))
if val>=0:
    if val==0:
        print("Entered a Zero Value")
    else:
        print("Entered number is Positive")
        
else:
    print("The Entered number is Negative")
    

Enter a float point number:-12
The Entered number is Negative


In [62]:
a,b,c,d=10,11,12,13

if a==10 or b==11 and c==12 and d==113:
    print("Let's do something 1")

if (a==10 and b==11) or (c==12 and d==113):
    print("Let's do something 2")

if a==10 and b==11 and c==12 and d==113 or a==9:
    print("Let's do something 3")

if a==9 and b==11 and c==12 and d==13:
    print("Let's do something 4")

Let's do something 1
Let's do something 2


In [66]:
print(type(a)==int)

True


In [67]:
print(type(a) is int)

True


In [63]:
l1=[]
l2=[]

In [64]:
l1==l2 # here the value is  being compared

True

In [65]:
l1 is l2 #here the object is being compared

False

In [68]:
a=10
if a <10 and a==10:
    print("Try to do something")

In [69]:
a='python'
if a=="python" or a=="Python":
    print("This is truth")

This is truth


In [70]:
a=10
b=11
c=12
d=13

if a==9 or b==11 and c==12 and d==13:
    print("Let's do something")

Let's do something


In [71]:
d={'key1':'value1','key2':'sandy','key3':'Sandeep'}

In [72]:
if d['key1']=='value1' and d['key2']=='sandy' and d['key3']=="Kumar":
    print("All values are varified")
    print(d.values())
else:
    print("All values are not varified")
    

All values are not varified


In [73]:
d['key1']

'value1'

In [74]:
l=[1,2,3,4,5,'hello',234.45]

In [75]:
l[0]

1

In [76]:
l[2:5]

[3, 4, 5]

In [79]:
for i in l:
    if type(i)==int or type(i)==float:
        print(i+1)
    elif type(i)==str:
        print(i+str(1))

2
3
4
5
6
hello1
235.45


In [80]:
l

[1, 2, 3, 4, 5, 'hello', 234.45]

In [90]:
a=[9,8,7,6,4,3,2,10]

In [83]:
a

[9, 8, 7, 6, 4, 3, 2, 10]

In [82]:
for i in a:
    print(i, end=" ")

9 8 7 6 4 3 2 10 

In [86]:
l1=[]
for i in l:
    if type(i)==int:
        l1.append(i)

In [87]:
l1

[1, 2, 3, 4, 5]

In [93]:
l=[1,2,3,4,5,'hello',234.45]
a=[9,8,7,6,4,3,2,10]

for a in l:
    if type(a) ==int:
        print(a+1)
    elif type(a)==str:
        print(a+str(1))
    elif type(a) ==float:
        print(a+float(1))

2
3
4
5
6
hello1
235.45


In [97]:
l=[1,2,3,4,5,"car",6,7,8]
for i in l:
    if l.isnumeric(i):
        print(i)

AttributeError: 'list' object has no attribute 'isnumeric'

In [99]:
l=[]
name=input("Enter your name:")
if name=="Sandeep":
    l.append(name)
print(l)

Enter your name:Sandeep
['Sandeep']


In [1]:
l=[1,2,3,4,5,6,7,8,9,10,11]

In [5]:
l[0::2]

[1, 3, 5, 7, 9, 11]

In [6]:
l[1::2]

[2, 4, 6, 8, 10]

> #### For Loop

In [11]:
l=[1,2,3,4,"Sandeep",32.8,True]
for i in l:
    print(i)
else:
    print("Ohk")

1
2
3
4
Sandeep
32.8
True
Ohk


In [9]:
l

[1, 2, 3, 'Sandeep', 32.8, True]

In [12]:
for i in l:
    if i==4:
        break
    print(i)
else:
    print("Else block will execute only if For loop is goiing to Complete itself")

1
2
3


In [14]:
s="Defence"
for i in s:
    if i=='z':
        break
    print(i)
else:
    print("Original String",s)

D
e
f
e
n
c
e
Original String Defence


In [16]:
t=(4,5,6,7,8,6,'karma')
for i in t:
    print(i, end=" ")

4 5 6 7 8 6 karma 

In [17]:
b={4,5,6,7,7,7,7,7,7,7,7,8,"Karma"}

In [18]:
type(b)

set

In [19]:
b

{4, 5, 6, 7, 8, 'Karma'}

In [21]:
for i in b:
    print(i)

4
5
6
7
8
Karma


In [22]:
d={"key1":"Karma","Key2":"Python","Key3":"xyz"}
for i in d:
    print(i,":",d[i])

key1 : Karma
Key2 : Python
Key3 : xyz


In [23]:
list(range(9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [25]:
for i in range(9):
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 

In [26]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [27]:
list(range(0,9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [31]:
list(range(9,0,-1))

[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [32]:
n=4
for i in range(4):
    for j in range(i+1):
        print('class',end =" ")
    print("\n")

class 

class class 

class class class 

class class class class 



In [34]:
n=3
for i in range(n):
    for j in range(i,n-1):
        print(" "* len("Class"),end=" ")
    for j in range(i+1):
        print("Class",end=" ")
    for j in range(i):
        print("Class",end=" ")
    print()

            Class 
      Class Class Class 
Class Class Class Class Class 


In [38]:
n=4
k=n
for i  in range(n):
    k=k-1 
    print("   "*k,end="  ")
    for j in range(i+1):
        print("Class",end=" ")
    print()

           Class 
        Class Class 
     Class Class Class 
  Class Class Class Class 


In [39]:
n=3
for i in range(n):
    for j in range(i,n-1):
        print("",end=" ")
    for j in range(i+1):
        print("Class",end=" ")
    print()

  Class 
 Class Class 
Class Class Class 


In [45]:
n=3
for i in range(n+1):
    print("  "*(n-i)+" class "*i)

      
      class 
    class   class 
  class   class   class 


In [46]:
list(range(0))

[]

In [47]:
t=(3,23,45,67,2,4,5,6)

In [48]:
t[0]

3

In [49]:
for i in range(len(t)):
    print(i,t[i])

0 3
1 23
2 45
3 67
4 2
5 4
6 5
7 6


In [50]:
list(range(len(t)))

[0, 1, 2, 3, 4, 5, 6, 7]

In [52]:
s="Sandeep"

for i in range(len(s)):
    print(i,s[i])

0 S
1 a
2 n
3 d
4 e
5 e
6 p


In [53]:
for i in d.items():
    print(i, type(i),type(i[1]))

('key1', 'Karma') <class 'tuple'> <class 'str'>
('Key2', 'Python') <class 'tuple'> <class 'str'>
('Key3', 'xyz') <class 'tuple'> <class 'str'>


In [58]:
s='aaaaabbccd'

In [60]:
for i  in set(s):
    print(i,":",s.count(i))

d : 1
c : 2
b : 2
a : 5


In [62]:
s.count('a')

5

In [64]:
i=34534654664525

for j in str(i):
    print(int(j),type(int(j)))

3 <class 'int'>
4 <class 'int'>
5 <class 'int'>
3 <class 'int'>
4 <class 'int'>
6 <class 'int'>
5 <class 'int'>
4 <class 'int'>
6 <class 'int'>
6 <class 'int'>
4 <class 'int'>
5 <class 'int'>
2 <class 'int'>
5 <class 'int'>


In [72]:
t=("Python","Class",[1,2,3,4,5],(3,4,5,6),{3:4,"Key1":"Web",3:"a","key2":"b","key3":"c"})

In [73]:
for i in t:
    if type(i) == list or type(i)==tuple:
        for j in i:
            if j==3:
                print(j)
    if type(i) ==dict:
        for k,l in i.items():
            if k==3 or l==3:
                print(k)
                print(l)

3
3
3
a


In [74]:
d={4:5,"key1":"py","key2":"Version"}

In [75]:
d.items()

dict_items([(4, 5), ('key1', 'py'), ('key2', 'Version')])

In [76]:
for i in d.items():
    print(i)

(4, 5)
('key1', 'py')
('key2', 'Version')


In [77]:
a=10
b=20
c=30

In [78]:
a,b,c=10,20,30

In [79]:
a

10

In [80]:
a,b,c=(10,20,30)

In [81]:
a

10

In [83]:
a=1
b=10

while a<=10:
    print(a)
    if a==5:
        break
    a=a+1
else:
    print("Nothing")

1
2
3
4
5


In [85]:
a=1
b=10

while a<b:
    a=a+1
    if a==3:
        pass
    print(a)

2
3
4
5
6
7
8
9
10


In [87]:
a=1
b=10

while a<b:
    a=a+1
    if a==3:
        pass
        print(a)

3


In [92]:
l=[1,2,3,4,56,67,8]

a=0

while a<len(l):
    print(l[a])
    a=a+1

1
2
3
4
56
67
8


In [93]:
t=(3,4,45,6,67,8,8,7)

In [98]:
i=0
while i<len(l):
    if (t[i]==6) or (t[i]==7):
        print(i)
    if i== -len(t):
        break
    i-=1
    i=i-1

-4


IndexError: tuple index out of range

In [99]:
a=-1
while a>= -len(t):
    if t[a]==6 or t[a]==7:
        print("Index of",t[a],"is",a)
    a=a-1

Index of 6 is -4


In [102]:
d={'k1':"Value-1","k2":"Value-2","k3":"Value-3"}

a=0
b=list(d.keys())

while a <len(d):
    print(d[b[a]])
    
    a=a+1

Value-1
Value-2
Value-3


In [103]:
b=list(d.keys())

In [104]:
b

['k1', 'k2', 'k3']

>#### Function

In [108]:
def test():
    print("This is the First Function")

In [110]:
str(test())+ "Sandy"

This is the First Function


'NoneSandy'

In [111]:
type(test())

This is the First Function


NoneType

In [123]:
def test2():
    a=4*5
    b=6+4
    c=1+2
    return a,b,c

In [124]:
g=test2()

In [125]:
g

(20, 10, 3)

In [127]:
g,k,d=test2()

In [128]:
g

20

In [129]:
k

10

In [130]:
d

3

In [132]:
_,_,g=test2()

In [133]:
g

3

In [134]:
a=1
b=10

while a<=b:
    print(a)
    a=a+2
else:
    print("Else Block executed")

1
3
5
7
9
Else Block executed


In [137]:
def test3(a,b):
    l=[]
    while a<=b:
        l.append(a)
        a=a+2
    else:
        print("Else Block")
    return l

In [138]:
test3(1,10)

Else Block


[1, 3, 5, 7, 9]

In [139]:
type(test3(30,2))

Else Block


list

In [140]:
l=[4,5,6,67,8,3,7,9,34,3,7,[3,4,5,6,7],"Python"]

In [145]:
l1=[]
l2=[]
for i in l:
    if type(i)==int:
        l1.append(i)
    else:
        l2.append(i)


In [146]:
l1

[4, 5, 6, 67, 8, 3, 7, 9, 34, 3, 7]

In [147]:
l2

[[3, 4, 5, 6, 7], 'Python']

In [150]:
def test4():
    l1=[]
    for i in l:
        if type(i)==int:
            l1.append(i)
    return l1

In [151]:
test4()

[4, 5, 6, 67, 8, 3, 7, 9, 34, 3, 7]

In [152]:
l3=[345,45,24,25,2,"Python",(1,3,4,5)]

In [154]:
def test5(l):
    l1=[]
    for i in l:
        if type(i)==int:
            l1.append(i)
    return l1

In [155]:
test5(l3)

[345, 45, 24, 25, 2]

In [156]:
def test6(t):
    a=-1
    while a>= -len(t):
        if t[a]==6 or t[a]==7:
            print("Index of",t[a],"is",a)
        a=a-1

In [157]:
test6(t)

Index of 6 is -4


In [159]:
test6((1,3,45,6,7,23,77,7,6,7,8,9,12))

Index of 7 is -4
Index of 6 is -5
Index of 7 is -6
Index of 7 is -9
Index of 6 is -10


In [163]:
# Q3 try to print all the number divisible by 3 in the range of 40 to 400

l=[]
for i in range(40,401):
    if i%3==0:
        l.append(i)

In [164]:
l

[42,
 45,
 48,
 51,
 54,
 57,
 60,
 63,
 66,
 69,
 72,
 75,
 78,
 81,
 84,
 87,
 90,
 93,
 96,
 99,
 102,
 105,
 108,
 111,
 114,
 117,
 120,
 123,
 126,
 129,
 132,
 135,
 138,
 141,
 144,
 147,
 150,
 153,
 156,
 159,
 162,
 165,
 168,
 171,
 174,
 177,
 180,
 183,
 186,
 189,
 192,
 195,
 198,
 201,
 204,
 207,
 210,
 213,
 216,
 219,
 222,
 225,
 228,
 231,
 234,
 237,
 240,
 243,
 246,
 249,
 252,
 255,
 258,
 261,
 264,
 267,
 270,
 273,
 276,
 279,
 282,
 285,
 288,
 291,
 294,
 297,
 300,
 303,
 306,
 309,
 312,
 315,
 318,
 321,
 324,
 327,
 330,
 333,
 336,
 339,
 342,
 345,
 348,
 351,
 354,
 357,
 360,
 363,
 366,
 369,
 372,
 375,
 378,
 381,
 384,
 387,
 390,
 393,
 396,
 399]

In [8]:
l=[1,2,3,43,5,6,8]
for i in l:
    if i%2==0:
        print(i, "is Divisible by 2")
    elif i%3==0:
        print(i, "is Divisible by 3")
    else:
        print(i)

1
2 is Divisible by 2
3 is Divisible by 3
43
5
6 is Divisible by 2
8 is Divisible by 2


> #### Data Analysis using Pandas, Numpy and Matplotlib

In [9]:
# Numpy
import numpy as np

In [10]:
l=[1,2,3,4,5,6]

np.array(l)

array([1, 2, 3, 4, 5, 6])

In [11]:
type(l)

list

In [12]:
l1=[1,2,3,"Python",344.3,6,4]

In [16]:
a1=np.array(l1)

In [17]:
a1

array(['1', '2', '3', 'Python', '344.3', '6', '4'], dtype='<U32')

In [26]:
a2=np.array([[1,2,3],[5,56,7]])

In [27]:
a2

array([[ 1,  2,  3],
       [ 5, 56,  7]])

In [28]:
a3=np.array([[[1,2,3],[34,5,6],[6,7,8]]])

In [29]:
a3

array([[[ 1,  2,  3],
        [34,  5,  6],
        [ 6,  7,  8]]])

In [25]:
type(a3)

numpy.ndarray

In [30]:
a1.ndim

1

In [31]:
a2.ndim

2

In [32]:
a3.ndim

3

In [33]:
a1.size

7

In [34]:
a1.shape

(7,)

In [35]:
help(a1.size)

Help on int object:

class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
 |  
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |  
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |  
 |  Built-in subclasses:
 |      bool
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      True if self else False
 |

In [36]:
a2.size

6

In [37]:
a2.shape

(2, 3)

In [38]:
a3.size

9

In [39]:
a3.shape

(1, 3, 3)

In [40]:
a1

array(['1', '2', '3', 'Python', '344.3', '6', '4'], dtype='<U32')

In [41]:
np.random.randint(2,50,(3,4))

array([[10, 20, 42,  3],
       [18, 23, 43, 12],
       [30, 25, 30,  8]])

In [44]:
np.random.randint(1,30,(2,3,4))

array([[[15, 18,  1, 19],
        [29, 15, 22,  1],
        [ 7,  3, 18,  2]],

       [[13,  3, 15, 28],
        [25, 24, 24, 12],
        [ 3, 12,  5, 28]]])

In [46]:
help(np.random.randint(1,30,(2,3,4)))

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [47]:
np.random.rand(5,4)

array([[0.01091767, 0.76803748, 0.10022426, 0.09204699],
       [0.56779375, 0.90336489, 0.95740617, 0.19040807],
       [0.72401434, 0.1200218 , 0.0829744 , 0.56459369],
       [0.07261367, 0.4694282 , 0.27264593, 0.56670562],
       [0.71001489, 0.0723007 , 0.70565777, 0.72525598]])

In [49]:
a=np.random.randn(3,4)

In [50]:
a

array([[-1.43390502, -0.95106102,  0.05952026,  0.24344846],
       [-0.25529029,  0.25111657, -1.1145409 ,  0.66814001],
       [ 0.58159848,  0.64437975,  0.38328889,  0.8141099 ]])

In [53]:
a.reshape(4,3)

array([[-1.43390502, -0.95106102,  0.05952026],
       [ 0.24344846, -0.25529029,  0.25111657],
       [-1.1145409 ,  0.66814001,  0.58159848],
       [ 0.64437975,  0.38328889,  0.8141099 ]])

In [54]:
a.reshape(2,6)

array([[-1.43390502, -0.95106102,  0.05952026,  0.24344846, -0.25529029,
         0.25111657],
       [-1.1145409 ,  0.66814001,  0.58159848,  0.64437975,  0.38328889,
         0.8141099 ]])

In [55]:
a.reshape(6,2)

array([[-1.43390502, -0.95106102],
       [ 0.05952026,  0.24344846],
       [-0.25529029,  0.25111657],
       [-1.1145409 ,  0.66814001],
       [ 0.58159848,  0.64437975],
       [ 0.38328889,  0.8141099 ]])

In [57]:
a.reshape(1,12)

array([[-1.43390502, -0.95106102,  0.05952026,  0.24344846, -0.25529029,
         0.25111657, -1.1145409 ,  0.66814001,  0.58159848,  0.64437975,
         0.38328889,  0.8141099 ]])

In [58]:
a.reshape(12,1)

array([[-1.43390502],
       [-0.95106102],
       [ 0.05952026],
       [ 0.24344846],
       [-0.25529029],
       [ 0.25111657],
       [-1.1145409 ],
       [ 0.66814001],
       [ 0.58159848],
       [ 0.64437975],
       [ 0.38328889],
       [ 0.8141099 ]])

In [60]:
a.reshape(2,-1212343)

array([[-1.43390502, -0.95106102,  0.05952026,  0.24344846, -0.25529029,
         0.25111657],
       [-1.1145409 ,  0.66814001,  0.58159848,  0.64437975,  0.38328889,
         0.8141099 ]])

In [68]:
a.reshape(1,1,1,1,1,1,2,2,3)

array([[[[[[[[[-1.43390502, -0.95106102,  0.05952026],
              [ 0.24344846, -0.25529029,  0.25111657]],

             [[-1.1145409 ,  0.66814001,  0.58159848],
              [ 0.64437975,  0.38328889,  0.8141099 ]]]]]]]]])

In [64]:
a1[::]

array(['1', '2', '3', 'Python', '344.3', '6', '4'], dtype='<U32')

In [65]:
a1[2:6]

array(['3', 'Python', '344.3', '6'], dtype='<U32')

In [73]:
a1[2:6:2]

array(['3', '344.3'], dtype='<U32')

In [74]:
a2[::]

array([[ 1,  2,  3],
       [ 5, 56,  7]])

In [75]:
a2[:,[1,2]]

array([[ 2,  3],
       [56,  7]])

In [78]:
b=np.random.randint(1,40,(3,4))

In [79]:
b

array([[29, 10, 32, 37],
       [36, 36,  5, 28],
       [23,  5,  7, 29]])

In [84]:
b1=b[b>10]

In [85]:
b1

array([29, 32, 37, 36, 36, 28, 23, 29])

In [82]:
b2=b[b<=10]

In [83]:
b2

array([10,  5,  5,  7])

In [87]:
b[2,2]=1000

In [88]:
b

array([[  29,   10,   32,   37],
       [  36,   36,    5,   28],
       [  23,    5, 1000,   29]])

In [90]:
c=np.random.randint(0,3,(3,3))

In [91]:
c

array([[0, 2, 0],
       [0, 1, 1],
       [1, 2, 0]])

In [92]:
d=np.random.randint(0,3,(3,3))

In [93]:
d

array([[1, 0, 0],
       [0, 0, 0],
       [2, 1, 2]])

In [94]:
c+d

array([[1, 2, 0],
       [0, 1, 1],
       [3, 3, 2]])

In [95]:
c@d

array([[0, 0, 0],
       [2, 1, 2],
       [1, 0, 0]])

In [97]:
d

array([[1, 0, 0],
       [0, 0, 0],
       [2, 1, 2]])

In [98]:
c+10

array([[10, 12, 10],
       [10, 11, 11],
       [11, 12, 10]])

In [99]:
c-5

array([[-5, -3, -5],
       [-5, -4, -4],
       [-4, -3, -5]])

In [100]:
d*2

array([[2, 0, 0],
       [0, 0, 0],
       [4, 2, 4]])

In [101]:
d/2

array([[0.5, 0. , 0. ],
       [0. , 0. , 0. ],
       [1. , 0.5, 1. ]])

In [103]:
m=np.zeros((4,5))

In [104]:
m

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [105]:
n=np.ones((2,3))

In [106]:
n

array([[1., 1., 1.],
       [1., 1., 1.]])

In [107]:
np.array(m).T

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [108]:
np.sqrt(c)

array([[0.        , 1.41421356, 0.        ],
       [0.        , 1.        , 1.        ],
       [1.        , 1.41421356, 0.        ]])

In [110]:
np.exp(d)

array([[2.71828183, 1.        , 1.        ],
       [1.        , 1.        , 1.        ],
       [7.3890561 , 2.71828183, 7.3890561 ]])

In [111]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [114]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [115]:
np.linspace(2,5,num=100,retstep=True)

(array([2.        , 2.03030303, 2.06060606, 2.09090909, 2.12121212,
        2.15151515, 2.18181818, 2.21212121, 2.24242424, 2.27272727,
        2.3030303 , 2.33333333, 2.36363636, 2.39393939, 2.42424242,
        2.45454545, 2.48484848, 2.51515152, 2.54545455, 2.57575758,
        2.60606061, 2.63636364, 2.66666667, 2.6969697 , 2.72727273,
        2.75757576, 2.78787879, 2.81818182, 2.84848485, 2.87878788,
        2.90909091, 2.93939394, 2.96969697, 3.        , 3.03030303,
        3.06060606, 3.09090909, 3.12121212, 3.15151515, 3.18181818,
        3.21212121, 3.24242424, 3.27272727, 3.3030303 , 3.33333333,
        3.36363636, 3.39393939, 3.42424242, 3.45454545, 3.48484848,
        3.51515152, 3.54545455, 3.57575758, 3.60606061, 3.63636364,
        3.66666667, 3.6969697 , 3.72727273, 3.75757576, 3.78787879,
        3.81818182, 3.84848485, 3.87878788, 3.90909091, 3.93939394,
        3.96969697, 4.        , 4.03030303, 4.06060606, 4.09090909,
        4.12121212, 4.15151515, 4.18181818, 4.21

In [118]:
np.linspace(2,4,num=7)

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        ])

In [119]:
np.logspace(2,4,num=5,base=10)

array([  100.        ,   316.22776602,  1000.        ,  3162.27766017,
       10000.        ])

In [120]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

> #### Data Analysis using Pandas

In [121]:
import pandas as pd

In [123]:
data={
    'name':['py','pyc','python','class'],
    'Salary':[100,120,110,150],
    "mail_id":['a@gmail.com','b@gmail.com','c@gmail.com','d@gmail.com'],
    "addr":['Blr','Pune','DL','Patna']
     }

In [124]:
df=pd.DataFrame(data)

In [125]:
df

name  Salary      mail_id   addr
0      py     100  a@gmail.com    Blr
1     pyc     120  b@gmail.com   Pune
2  python     110  c@gmail.com     DL
3   class     150  d@gmail.com  Patna

In [126]:
df.head(2)

name  Salary      mail_id  addr
0   py     100  a@gmail.com   Blr
1  pyc     120  b@gmail.com  Pune

In [127]:
df.tail(2)

name  Salary      mail_id   addr
2  python     110  c@gmail.com     DL
3   class     150  d@gmail.com  Patna

In [128]:
df.loc[5:6]

Empty DataFrame
Columns: [name, Salary, mail_id, addr]
Index: []

In [129]:
df.iloc[1:3]

name  Salary      mail_id  addr
1     pyc     120  b@gmail.com  Pune
2  python     110  c@gmail.com    DL

In [132]:
data1={
    'pf_num':[23,64,79,26],
    'income_tax':[435,35,246,33],
    'Mob_Num':[123,345,456,237],
    'Course':['DS','Web Dev','Cloud','Blockchain']
}

In [133]:
df1=pd.DataFrame(data1)

In [134]:
df1

pf_num  income_tax  Mob_Num      Course
0      23         435      123          DS
1      64          35      345     Web Dev
2      79         246      456       Cloud
3      26          33      237  Blockchain

In [135]:
max(df1['income_tax'])

435

In [136]:
min(df1['income_tax'])

33

In [138]:
type(df1)

pandas.core.frame.DataFrame

In [140]:
type(df1['pf_num'])

pandas.core.series.Series

In [143]:
df2=pd.concat([df,df1])

In [144]:
df2

name  Salary      mail_id   addr  pf_num  income_tax  Mob_Num      Course
0      py   100.0  a@gmail.com    Blr     NaN         NaN      NaN         NaN
1     pyc   120.0  b@gmail.com   Pune     NaN         NaN      NaN         NaN
2  python   110.0  c@gmail.com     DL     NaN         NaN      NaN         NaN
3   class   150.0  d@gmail.com  Patna     NaN         NaN      NaN         NaN
0     NaN     NaN          NaN    NaN    23.0       435.0    123.0          DS
1     NaN     NaN          NaN    NaN    64.0        35.0    345.0     Web Dev
2     NaN     NaN          NaN    NaN    79.0       246.0    456.0       Cloud
3     NaN     NaN          NaN    NaN    26.0        33.0    237.0  Blockchain

In [148]:
df3=pd.concat([df,df1],axis=1)

In [149]:
df3

name  Salary      mail_id   addr  pf_num  income_tax  Mob_Num      Course
0      py     100  a@gmail.com    Blr      23         435      123          DS
1     pyc     120  b@gmail.com   Pune      64          35      345     Web Dev
2  python     110  c@gmail.com     DL      79         246      456       Cloud
3   class     150  d@gmail.com  Patna      26          33      237  Blockchain

In [151]:
data4={
    '0':['py','pyc','python','class'],
    '1':[100,120,110,150],
    "2":['a@gmail.com','b@gmail.com','c@gmail.com','d@gmail.com'],
    "3":['Blr','Pune','DL','Patna']
     }

In [153]:
d4=pd.DataFrame(data4)

In [152]:
data5={
    '0':[23,64,79,26],
    '1':[435,35,246,33],
    '2':[123,345,456,237],
    '3':['DS','Web Dev','Cloud','Blockchain']
}

In [154]:
d5=pd.DataFrame(data5)

In [157]:
new_df=pd.concat([d4,d5],axis=0)

In [158]:
new_df

0    1            2           3
0      py  100  a@gmail.com         Blr
1     pyc  120  b@gmail.com        Pune
2  python  110  c@gmail.com          DL
3   class  150  d@gmail.com       Patna
0      23  435          123          DS
1      64   35          345     Web Dev
2      79  246          456       Cloud
3      26   33          237  Blockchain

In [162]:
d={
    'emp_id':[1,2,3,4],
    'Salary':[200,230,300,250],
    'Pf':[20,30,35,22]
}

In [166]:
d1={
    'emp_id':[1,2,3,4],
    'Mob_Num':[234,245,325,225],
    'House_Num':[320,502,240,248]
}

In [167]:
df=pd.DataFrame(d)

In [168]:
df1=pd.DataFrame(d1)

In [169]:
df

emp_id  Salary  Pf
0       1     200  20
1       2     230  30
2       3     300  35
3       4     250  22

In [170]:
df1

emp_id  Mob_Num  House_Num
0       1      234        320
1       2      245        502
2       3      325        240
3       4      225        248

In [172]:
Com=pd.merge(df,df1,how='left')

In [173]:
Com

emp_id  Salary  Pf  Mob_Num  House_Num
0       1     200  20      234        320
1       2     230  30      245        502
2       3     300  35      325        240
3       4     250  22      225        248

In [175]:
pd.merge(df,df1,how='left',on='emp_id')

emp_id  Salary  Pf  Mob_Num  House_Num
0       1     200  20      234        320
1       2     230  30      245        502
2       3     300  35      325        240
3       4     250  22      225        248

>#### Machine Learning

In [1]:
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_csv("C:\\Users\\sande\\College\\Bootcamp\\archive\\car data.csv")
df2=pd.read_csv("C:\\Users\\sande\\College\\Bootcamp\\archive\\CAR DETAILS FROM CAR DEKHO.csv")
df3=pd.read_csv("C:\\Users\\sande\\College\\Bootcamp\\archive\\Car details v3.csv")
df4=pd.read_csv("C:\\Users\\sande\\College\\Bootcamp\\archive\\car details v4.csv")

In [3]:
df1.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

In [4]:
df2

name  year  selling_price  km_driven  \
0                           Maruti 800 AC  2007          60000      70000   
1                Maruti Wagon R LXI Minor  2007         135000      50000   
2                    Hyundai Verna 1.6 SX  2012         600000     100000   
3                  Datsun RediGO T Option  2017         250000      46000   
4                   Honda Amaze VX i-DTEC  2014         450000     141000   
...                                   ...   ...            ...        ...   
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999      80000   
4336           Hyundai i20 Magna 1.4 CRDi  2014         409999      80000   
4337                  Maruti 800 AC BSIII  2009         110000      83000   
4338     Hyundai Creta 1.6 CRDi SX Option  2016         865000      90000   
4339                     Renault KWID RXT  2016         225000      40000   

        fuel seller_type transmission         owner  
0     Petrol  Individual       Manual   First Owner  
1     Petrol  Individual       Manual   First Owner  
2     Diesel  Individual       Manual   First Owner  
3     Petrol  Individual       Manual   First Owner  
4     Diesel  Individual       Manual  Second Owner  
...      ...         ...          ...           ...  
4335  Diesel  Individual       Manual  Second Owner  
4336  Diesel  Individual       Manual  Second Owner  
4337  Petrol  Individual       Manual  Second Owner  
4338  Diesel  Individual       Manual   First Owner  
4339  Petrol  Individual       Manual   First Owner  

[4340 rows x 8 columns]

In [5]:
df3

name  year  selling_price  km_driven    fuel  \
0           Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1     Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2         Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3        Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4           Maruti Swift VXI BSIII  2007         130000     120000  Petrol   
...                            ...   ...            ...        ...     ...   
8123             Hyundai i20 Magna  2013         320000     110000  Petrol   
8124         Hyundai Verna CRDi SX  2007         135000     119000  Diesel   
8125        Maruti Swift Dzire ZDi  2009         382000     120000  Diesel   
8126               Tata Indigo CR4  2013         290000      25000  Diesel   
8127               Tata Indigo CR4  2013         290000      25000  Diesel   

     seller_type transmission                 owner     mileage   engine  \
0     Individual       Manual           First Owner   23.4 kmpl  1248 CC   
1     Individual       Manual          Second Owner  21.14 kmpl  1498 CC   
2     Individual       Manual           Third Owner   17.7 kmpl  1497 CC   
3     Individual       Manual           First Owner   23.0 kmpl  1396 CC   
4     Individual       Manual           First Owner   16.1 kmpl  1298 CC   
...          ...          ...                   ...         ...      ...   
8123  Individual       Manual           First Owner   18.5 kmpl  1197 CC   
8124  Individual       Manual  Fourth & Above Owner   16.8 kmpl  1493 CC   
8125  Individual       Manual           First Owner   19.3 kmpl  1248 CC   
8126  Individual       Manual           First Owner  23.57 kmpl  1396 CC   
8127  Individual       Manual           First Owner  23.57 kmpl  1396 CC   

       max_power                     torque  seats  
0         74 bhp             190Nm@ 2000rpm    5.0  
1     103.52 bhp        250Nm@ 1500-2500rpm    5.0  
2         78 bhp      12.7@ 2,700(kgm@ rpm)    5.0  
3         90 bhp   22.4 kgm at 1750-2750rpm    5.0  
4       88.2 bhp      11.5@ 4,500(kgm@ rpm)    5.0  
...          ...                        ...    ...  
8123   82.85 bhp           113.7Nm@ 4000rpm    5.0  
8124     110 bhp  24@ 1,900-2,750(kgm@ rpm)    5.0  
8125    73.9 bhp             190Nm@ 2000rpm    5.0  
8126      70 bhp        140Nm@ 1800-3000rpm    5.0  
8127      70 bhp        140Nm@ 1800-3000rpm    5.0  

[8128 rows x 13 columns]

In [6]:
df4

Make                                  Model    Price  Year  \
0             Honda                    Amaze 1.2 VX i-VTEC   505000  2017   
1     Maruti Suzuki                        Swift DZire VDI   450000  2014   
2           Hyundai                   i10 Magna 1.2 Kappa2   220000  2011   
3            Toyota                               Glanza G   799000  2019   
4            Toyota        Innova 2.4 VX 7 STR [2016-2020]  1950000  2018   
...             ...                                    ...      ...   ...   
2054       Mahindra                  XUV500 W8 [2015-2017]   850000  2016   
2055        Hyundai                           Eon D-Lite +   275000  2014   
2056           Ford            Figo Duratec Petrol ZXI 1.2   240000  2013   
2057            BMW  5-Series 520d Luxury Line [2017-2019]  4290000  2018   
2058       Mahindra      Bolero Power Plus ZLX [2016-2019]   670000  2017   

      Kilometer Fuel Type Transmission    Location   Color   Owner  \
0         87150    Petrol       Manual        Pune    Grey   First   
1         75000    Diesel       Manual    Ludhiana   White  Second   
2         67000    Petrol       Manual     Lucknow  Maroon   First   
3         37500    Petrol       Manual   Mangalore     Red   First   
4         69000    Diesel       Manual      Mumbai    Grey   First   
...         ...       ...          ...         ...     ...     ...   
2054      90300    Diesel       Manual       Surat   White   First   
2055      83000    Petrol       Manual   Ahmedabad   White  Second   
2056      73000    Petrol       Manual       Thane  Silver   First   
2057      60474    Diesel    Automatic  Coimbatore   White   First   
2058      72000    Diesel       Manual    Guwahati   White   First   

     Seller Type   Engine           Max Power              Max Torque  \
0      Corporate  1198 cc   87 bhp @ 6000 rpm       109 Nm @ 4500 rpm   
1     Individual  1248 cc   74 bhp @ 4000 rpm       190 Nm @ 2000 rpm   
2     Individual  1197 cc   79 bhp @ 6000 rpm  112.7619 Nm @ 4000 rpm   
3     Individual  1197 cc   82 bhp @ 6000 rpm       113 Nm @ 4200 rpm   
4     Individual  2393 cc  148 bhp @ 3400 rpm       343 Nm @ 1400 rpm   
...          ...      ...                 ...                     ...   
2054  Individual  2179 cc  138 bhp @ 3750 rpm       330 Nm @ 1600 rpm   
2055  Individual   814 cc   55 bhp @ 5500 rpm        75 Nm @ 4000 rpm   
2056  Individual  1196 cc   70 bhp @ 6250 rpm       102 Nm @ 4000 rpm   
2057  Individual  1995 cc  188 bhp @ 4000 rpm       400 Nm @ 1750 rpm   
2058  Individual  1493 cc   70 bhp @ 3600 rpm       195 Nm @ 1400 rpm   

     Drivetrain  Length   Width  Height  Seating Capacity  Fuel Tank Capacity  
0           FWD  3990.0  1680.0  1505.0               5.0                35.0  
1           FWD  3995.0  1695.0  1555.0               5.0                42.0  
2           FWD  3585.0  1595.0  1550.0               5.0                35.0  
3           FWD  3995.0  1745.0  1510.0               5.0                37.0  
4           RWD  4735.0  1830.0  1795.0               7.0                55.0  
...         ...     ...     ...     ...               ...                 ...  
2054        FWD  4585.0  1890.0  1785.0               7.0                70.0  
2055        FWD  3495.0  1550.0  1500.0               5.0                32.0  
2056        FWD  3795.0  1680.0  1427.0               5.0                45.0  
2057        RWD  4936.0  1868.0  1479.0               5.0                65.0  
2058        RWD  3995.0  1745.0  1880.0               7.0                 NaN  

[2059 rows x 20 columns]

In [7]:
df1.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [8]:
df2.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [9]:
df3.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [10]:
df4.isnull().sum()

Make                    0
Model                   0
Price                   0
Year                    0
Kilometer               0
Fuel Type               0
Transmission            0
Location                0
Color                   0
Owner                   0
Seller Type             0
Engine                 80
Max Power              80
Max Torque             80
Drivetrain            136
Length                 64
Width                  64
Height                 64
Seating Capacity       64
Fuel Tank Capacity    113
dtype: int64

In [11]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Seller_Type    301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


In [12]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   name           4340 non-null   object
 1   year           4340 non-null   int64 
 2   selling_price  4340 non-null   int64 
 3   km_driven      4340 non-null   int64 
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB


In [13]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   name           8128 non-null   object 
 1   year           8128 non-null   int64  
 2   selling_price  8128 non-null   int64  
 3   km_driven      8128 non-null   int64  
 4   fuel           8128 non-null   object 
 5   seller_type    8128 non-null   object 
 6   transmission   8128 non-null   object 
 7   owner          8128 non-null   object 
 8   mileage        7907 non-null   object 
 9   engine         7907 non-null   object 
 10  max_power      7913 non-null   object 
 11  torque         7906 non-null   object 
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB


In [14]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2059 entries, 0 to 2058
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Make                2059 non-null   object 
 1   Model               2059 non-null   object 
 2   Price               2059 non-null   int64  
 3   Year                2059 non-null   int64  
 4   Kilometer           2059 non-null   int64  
 5   Fuel Type           2059 non-null   object 
 6   Transmission        2059 non-null   object 
 7   Location            2059 non-null   object 
 8   Color               2059 non-null   object 
 9   Owner               2059 non-null   object 
 10  Seller Type         2059 non-null   object 
 11  Engine              1979 non-null   object 
 12  Max Power           1979 non-null   object 
 13  Max Torque          1979 non-null   object 
 14  Drivetrain          1923 non-null   object 
 15  Length              1995 non-null   float64
 16  Width 

> #### Supervised ML

- SVM
    * SVC
    * SVR
 
 
- Logistic Regression
- Decision Tree
- Random Forest

In [33]:
# RUC and Area Under the RUC 

from sklearn.metrics import roc_curve, auc
from sklearn import datasets
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC
from sklearn.preprocessing import label_binarize
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

iris = datasets.load_iris()
X, y = iris.data, iris.target

y = label_binarize(y, classes=[0,1,2])
n_classes = 3

# shuffle and split training and test sets
X_train, X_test, y_train, y_test =\
    train_test_split(X, y, test_size=0.33, random_state=0)

# classifier
clf = OneVsRestClassifier(LinearSVC(random_state=0))
y_score = clf.fit(X_train, y_train).decision_function(X_test)

# Compute ROC curve and ROC area for each class
fpr = dict()
tpr = dict()
roc_auc = dict()
for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_test[:, i], y_score[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Plot of a ROC curve for a specific class
for i in range(n_classes):
    plt.figure()
    plt.plot(fpr[i], tpr[i], label='ROC curve (area = %0.2f)' % roc_auc[i])
    plt.plot([0, 1], [0, 1], 'k--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Receiver operating characteristic example')
    plt.legend(loc="lower right")
    plt.show()

C:\Users\sande\anaconda3\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning:

Liblinear failed to converge, increase the number of iterations.

C:\Users\sande\anaconda3\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning:

Liblinear failed to converge, increase the number of iterations.



> #### Random Forest

In [2]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

In [56]:
X,Y=make_classification(n_samples=1000,n_features=10,random_state=42) #Generated the dataset

In [70]:
#Splitting the Dataset into Training and Testing Purpose
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.25,random_state=42)

In [71]:
#Initialize the Random Forest
rf=RandomForestClassifier(n_estimators=89,random_state=42) #n_estimator = Number of trees in the Random Forest

In [72]:
#Training the Model
rf.fit(X_train,y_train)

RandomForestClassifier(n_estimators=89, random_state=42)

In [73]:
y_pred=rf.predict(X_test)

In [74]:
y_pred

array([0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0])

In [75]:
print(f"Accuracy is:{rf.score(x_test,y_test)}")

Accuracy is:0.896


> ### XGBoost

In [78]:
!pip install xgboost

In [98]:
import xgboost as xgb
from sklearn.metrics import accuracy_score

In [99]:
#Converting the Dataset Dmatrix format (Optimized for XGBoost)
dtrain=xgb.DMatrix(X_train,label=y_train)
dtest=xgb.DMatrix(X_test,label=y_test)

In [118]:
param={
    'objective':'binary:logistic', # for binary classification
    'max_depth':3,
    'learning_rate':0.1,
    'n_estimators':90
}

In [119]:
#Model Training
xgb_model=xgb.train(param,dtrain,num_boost_round=100)

C:\Users\sande\anaconda3\lib\site-packages\xgboost\core.py:158: UserWarning: [11:08:31] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0ed59c031377d09b8-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "n_estimators" } are not used.

  warnings.warn(smsg, UserWarning)


In [120]:
y_pred=xgb_model.predict(dtest)
y_pred_binary=[1 if pred > 0.5 else 0 for pred in y_pred]
accuracy = accuracy_score(y_test,y_pred_binary)

print(f"XGBoost Accuracy{accuracy}")

XGBoost Accuracy0.892


> ### Adaboost

In [121]:
from sklearn.ensemble import AdaBoostClassifier

In [122]:
ada = AdaBoostClassifier(n_estimators=50,random_state=42)

In [123]:
ada.fit(X_train,y_train)

AdaBoostClassifier(random_state=42)

In [124]:
y_pred=ada.predict(X_test)

In [125]:
y_pred

array([0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0])

In [126]:
print(f"AdaBoost Accuracy: {ada.score(X_test,y_test)}")

AdaBoost Accuracy: 0.86


> ### Gradient Descent

In [127]:
import numpy as np

In [128]:
X= np.array([1,2,3,4,5])
Y=np.array([5,7,9,11,13])

In [142]:
# Initialization of Parameters
m=b=0 #Slope and Intercept
lr=0.1 #Learning rate initialization
epoch=1000

In [143]:
for _ in range(epoch):
    y_pred =m*X+b # Predicted Value
    D_m=(-2/len(X)) * sum (X*(Y-y_pred)) #derivative wrt m
    D_b=(-2/len(X)) * sum(Y-y_pred) #derivative wrt b
    m -= lr* D_m #Update the value of m
    b -= lr*D_b # Update the Value of b

In [144]:
print(f"Slope:{m},Intercept:{b}")

Slope:-8.532027941246304e+135,Intercept:-2.3632349282172212e+135


In [2]:
#Question 01 without user input

import logging

# Configure logging to write to a file
logging.basicConfig(filename='matrix_operations.log', level=logging.ERROR, 
                    format='%(asctime)s:%(levelname)s:%(message)s')

# Function to add two matrices
def matrix_addition(A, B):
    try:
        # Check if matrices are empty
        if not A or not B:
            raise ValueError("One of the matrices is empty.")
        
        # Check if matrix dimensions match for addition
        if len(A) != len(B) or len(A[0]) != len(B[0]):
            raise ValueError("Matrix dimensions do not match for addition.")
        
        # Adding matrices element-wise using nested loops
        result = [[A[i][j] + B[i][j] for j in range(len(A[0]))] for i in range(len(A))]
        return result
    
    except Exception as e:
        logging.error(f"Matrix addition error: {e}")
        return str(e)

# Function to subtract two matrices
def matrix_subtraction(A, B):
    try:
        # Check if matrices are empty
        if not A or not B:
            raise ValueError("One of the matrices is empty.")
        
        # Check if matrix dimensions match for subtraction
        if len(A) != len(B) or len(A[0]) != len(B[0]):
            raise ValueError("Matrix dimensions do not match for subtraction.")
        
        # Subtracting matrices element-wise using nested loops
        result = [[A[i][j] - B[i][j] for j in range(len(A[0]))] for i in range(len(A))]
        return result
    
    except Exception as e:
        logging.error(f"Matrix subtraction error: {e}")
        return str(e)

# Function to multiply two matrices
def matrix_multiplication(A, B):
    try:
        # Check if matrices are empty
        if not A or not B:
            raise ValueError("One of the matrices is empty.")
        
        # Check if matrix dimensions match for multiplication
        if len(A[0]) != len(B):
            raise ValueError("Matrix dimensions do not match for multiplication.")
        
        # Multiplying matrices using nested loops
        result = [[sum(A[i][k] * B[k][j] for k in range(len(B))) for j in range(len(B[0]))] for i in range(len(A))]
        return result
    
    except Exception as e:
        logging.error(f"Matrix multiplication error: {e}")
        return str(e)

# Function to validate matrix entries
def validate_matrix(matrix):
    try:
        # Check if matrix is empty
        if not matrix:
            raise ValueError("Matrix is empty.")
        
        # Check if all entries in the matrix are numeric
        for row in matrix:
            if not all(isinstance(item, (int, float)) for item in row):
                raise ValueError("Matrix contains non-numeric entries.")
        
        return True
    
    except Exception as e:
        logging.error(f"Matrix validation error: {e}")
        return False

# Sample matrices for testing
matrix_A = [[3,6],[6,7]]
matrix_B = [[5, 6], [7, 8]]

# Matrix operations
if validate_matrix(matrix_A) and validate_matrix(matrix_B):
    print("Matrix Addition:")
    print(matrix_addition(matrix_A, matrix_B))

    print("\nMatrix Subtraction:")
    print(matrix_subtraction(matrix_A, matrix_B))

    print("\nMatrix Multiplication:")
    print(matrix_multiplication(matrix_A, matrix_B))
else:
    print("Invalid matrix input.")

Matrix Addition:
[[8, 12], [13, 15]]

Matrix Subtraction:
[[-2, 0], [-1, -1]]

Matrix Multiplication:
[[57, 66], [79, 92]]


In [7]:
import logging

# Configure logging
logging.basicConfig(filename='matrix_operations.log', level=logging.ERROR,
                    format='%(asctime)s:%(levelname)s:%(message)s')

# Function to check if a matrix is valid
def is_valid_matrix(matrix):
    if not matrix or not all(matrix):  # Check if matrix is empty or contains empty rows
        return False
    return True

# Function to check if all elements are numeric
def are_numeric_elements(matrix):
    try:
        for row in matrix:
            for element in row:
                float(element)  # Try converting to float
        return True
    except ValueError:
        return False

# Function to add two matrices
def add_matrices(matrix1, matrix2):
    try:
        if not (is_valid_matrix(matrix1) and is_valid_matrix(matrix2)):
            raise ValueError("One or both matrices are empty.")
        
        if len(matrix1) != len(matrix2) or len(matrix1[0]) != len(matrix2[0]):
            raise ValueError("Matrices must have the same dimensions for addition.")
        
        if not (are_numeric_elements(matrix1) and are_numeric_elements(matrix2)):
            raise ValueError("Matrices must contain only numeric values.")
        
        result = [[matrix1[i][j] + matrix2[i][j] for j in range(len(matrix1[0]))] for i in range(len(matrix1))]
        return result
    
    except ValueError as e:
        logging.error(e)
        print(f"Error: {e}")
        return None

# Function to subtract two matrices
def subtract_matrices(matrix1, matrix2):
    try:
        if not (is_valid_matrix(matrix1) and is_valid_matrix(matrix2)):
            raise ValueError("One or both matrices are empty.")
        
        if len(matrix1) != len(matrix2) or len(matrix1[0]) != len(matrix2[0]):
            raise ValueError("Matrices must have the same dimensions for subtraction.")
        
        if not (are_numeric_elements(matrix1) and are_numeric_elements(matrix2)):
            raise ValueError("Matrices must contain only numeric values.")
        
        result = [[matrix1[i][j] - matrix2[i][j] for j in range(len(matrix1[0]))] for i in range(len(matrix1))]
        return result
    
    except ValueError as e:
        logging.error(e)
        print(f"Error: {e}")
        return None

# Function to multiply two matrices
def multiply_matrices(matrix1, matrix2):
    try:
        if not (is_valid_matrix(matrix1) and is_valid_matrix(matrix2)):
            raise ValueError("One or both matrices are empty.")
        
        if len(matrix1[0]) != len(matrix2):
            raise ValueError("Matrices must have compatible dimensions for multiplication.")
        
        if not (are_numeric_elements(matrix1) and are_numeric_elements(matrix2)):
            raise ValueError("Matrices must contain only numeric values.")
        
        result = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(len(matrix2))) for j in range(len(matrix2[0]))] for i in range(len(matrix1))]
        return result
    
    except ValueError as e:
        logging.error(e)
        print(f"Error: {e}")
        return None

# Function to take matrix input from the user
def input_matrix(rows, cols):
    matrix = []
    print(f"Enter the elements for a {rows}x{cols} matrix row by row (separate by space):")
    for i in range(rows):
        while True:
            try:
                row = input(f"Enter row {i + 1}: ").split()
                if len(row) != cols:
                    raise ValueError("The number of elements in the row does not match the number of columns.")
                
                row = [float(x) for x in row]  # Convert all elements to float
                matrix.append(row)
                break
            except ValueError as e:
                print(f"Error: {e}")
                logging.error(e)
                print("Please re-enter the row correctly.")
    
    return matrix

# Main function to get user inputs and perform operations
def main():
    try:
        # Get matrix dimensions from the user
        rows1 = int(input("Enter the number of rows for Matrix 1: "))
        cols1 = int(input("Enter the number of columns for Matrix 1: "))
        matrix1 = input_matrix(rows1, cols1)
        
        rows2 = int(input("Enter the number of rows for Matrix 2: "))
        cols2 = int(input("Enter the number of columns for Matrix 2: "))
        matrix2 = input_matrix(rows2, cols2)
        
        # Ask the user which operation to perform
        print("\nChoose the operation you want to perform:")
        print("1. Addition")
        print("2. Subtraction")
        print("3. Multiplication")
        choice = int(input("Enter your choice (1/2/3): "))
        
        if choice == 1:
            if rows1 == rows2 and cols1 == cols2:
                result = add_matrices(matrix1, matrix2)
                if result:
                    print("\nMatrix Addition Result:")
                    for row in result:
                        print(row)
            else:
                print("Matrices must have the same dimensions for addition.")
        
        elif choice == 2:
            if rows1 == rows2 and cols1 == cols2:
                result = subtract_matrices(matrix1, matrix2)
                if result:
                    print("\nMatrix Subtraction Result:")
                    for row in result:
                        print(row)
            else:
                print("Matrices must have the same dimensions for subtraction.")
        
        elif choice == 3:
            if cols1 == rows2:
                result = multiply_matrices(matrix1, matrix2)
                if result:
                    print("\nMatrix Multiplication Result:")
                    for row in result:
                        print(row)
            else:
                print("Matrices must have compatible dimensions for multiplication.")
        
        else:
            print("Invalid choice. Please select 1, 2, or 3.")
    
    except ValueError as e:
        logging.error(e)
        print(f"Error: {e}")

# Run the main function
if __name__ == "__main__":
    main()
import logging

# Configure logging
logging.basicConfig(filename='matrix_operations.log', level=logging.ERROR,
                    format='%(asctime)s:%(levelname)s:%(message)s')

# Function to check if a matrix is valid
def is_valid_matrix(matrix):
    if not matrix or not all(matrix):  # Check if matrix is empty or contains empty rows
        return False
    return True

# Function to check if all elements are numeric
def are_numeric_elements(matrix):
    try:
        for row in matrix:
            for element in row:
                float(element)  # Try converting to float
        return True
    except ValueError:
        return False

# Function to add two matrices
def add_matrices(matrix1, matrix2):
    try:
        if not (is_valid_matrix(matrix1) and is_valid_matrix(matrix2)):
            raise ValueError("One or both matrices are empty.")
        
        if len(matrix1) != len(matrix2) or len(matrix1[0]) != len(matrix2[0]):
            raise ValueError("Matrices must have the same dimensions for addition.")
        
        if not (are_numeric_elements(matrix1) and are_numeric_elements(matrix2)):
            raise ValueError("Matrices must contain only numeric values.")
        
        result = [[matrix1[i][j] + matrix2[i][j] for j in range(len(matrix1[0]))] for i in range(len(matrix1))]
        return result
    
    except ValueError as e:
        logging.error(e)
        print(f"Error: {e}")
        return None

# Function to subtract two matrices
def subtract_matrices(matrix1, matrix2):
    try:
        if not (is_valid_matrix(matrix1) and is_valid_matrix(matrix2)):
            raise ValueError("One or both matrices are empty.")
        
        if len(matrix1) != len(matrix2) or len(matrix1[0]) != len(matrix2[0]):
            raise ValueError("Matrices must have the same dimensions for subtraction.")
        
        if not (are_numeric_elements(matrix1) and are_numeric_elements(matrix2)):
            raise ValueError("Matrices must contain only numeric values.")
        
        result = [[matrix1[i][j] - matrix2[i][j] for j in range(len(matrix1[0]))] for i in range(len(matrix1))]
        return result
    
    except ValueError as e:
        logging.error(e)
        print(f"Error: {e}")
        return None

# Function to multiply two matrices
def multiply_matrices(matrix1, matrix2):
    try:
        if not (is_valid_matrix(matrix1) and is_valid_matrix(matrix2)):
            raise ValueError("One or both matrices are empty.")
        
        if len(matrix1[0]) != len(matrix2):
            raise ValueError("Matrices must have compatible dimensions for multiplication.")
        
        if not (are_numeric_elements(matrix1) and are_numeric_elements(matrix2)):
            raise ValueError("Matrices must contain only numeric values.")
        
        result = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(len(matrix2))) for j in range(len(matrix2[0]))] for i in range(len(matrix1))]
        return result
    
    except ValueError as e:
        logging.error(e)
        print(f"Error: {e}")
        return None

# Function to take matrix input from the user
def input_matrix(rows, cols):
    matrix = []
    print(f"Enter the elements for a {rows}x{cols} matrix row by row (separate by space):")
    for i in range(rows):
        while True:
            try:
                row = input(f"Enter row {i + 1}: ").split()
                if len(row) != cols:
                    raise ValueError("The number of elements in the row does not match the number of columns.")
                
                row = [float(x) for x in row]  # Convert all elements to float
                matrix.append(row)
                break
            except ValueError as e:
                print(f"Error: {e}")
                logging.error(e)
                print("Please re-enter the row correctly.")
    
    return matrix

# Main function to get user inputs and perform operations
def main():
    try:
        # Get matrix dimensions from the user
        rows1 = int(input("Enter the number of rows for Matrix 1: "))
        cols1 = int(input("Enter the number of columns for Matrix 1: "))
        matrix1 = input_matrix(rows1, cols1)
        
        rows2 = int(input("Enter the number of rows for Matrix 2: "))
        cols2 = int(input("Enter the number of columns for Matrix 2: "))
        matrix2 = input_matrix(rows2, cols2)
        
        # Ask the user which operation to perform
        print("\nChoose the operation you want to perform:")
        print("1. Addition")
        print("2. Subtraction")
        print("3. Multiplication")
        choice = int(input("Enter your choice (1/2/3): "))
        
        if choice == 1:
            if rows1 == rows2 and cols1 == cols2:
                result = add_matrices(matrix1, matrix2)
                if result:
                    print("\nMatrix Addition Result:")
                    for row in result:
                        print(row)
            else:
                print("Matrices must have the same dimensions for addition.")
        
        elif choice == 2:
            if rows1 == rows2 and cols1 == cols2:
                result = subtract_matrices(matrix1, matrix2)
                if result:
                    print("\nMatrix Subtraction Result:")
                    for row in result:
                        print(row)
            else:
                print("Matrices must have the same dimensions for subtraction.")
        
        elif choice == 3:
            if cols1 == rows2:
                result = multiply_matrices(matrix1, matrix2)
                if result:
                    print("\nMatrix Multiplication Result:")
                    for row in result:
                        print(row)
            else:
                print("Matrices must have compatible dimensions for multiplication.")
        
        else:
            print("Invalid choice. Please select 1, 2, or 3.")
    
    except ValueError as e:
        logging.error(e)
        print(f"Error: {e}")

# Run the main function
if __name__ == "__main__":
    main()


Enter the number of rows for Matrix 1: 2
Enter the number of columns for Matrix 1: 2
Enter the elements for a 2x2 matrix row by row (separate by space):
Enter row 1: 2 6
Enter row 2: 6 4
Enter the number of rows for Matrix 2: 2
Enter the number of columns for Matrix 2: 2
Enter the elements for a 2x2 matrix row by row (separate by space):
Enter row 1: 7 3
Enter row 2: 9 6

Choose the operation you want to perform:
1. Addition
2. Subtraction
3. Multiplication
Enter your choice (1/2/3): 1

Matrix Addition Result:
[9.0, 9.0]
[15.0, 10.0]
Enter the number of rows for Matrix 1: s
Error: invalid literal for int() with base 10: 's'


In [6]:
# Question 2

import logging

# Configure logging
logging.basicConfig(filename='file_processing.log', level=logging.ERROR,
                    format='%(asctime)s:%(levelname)s:%(message)s')

# Function to process each line of the file
def process_line(line):
    try:
        # Split the line into parts based on commas
        parts = line.strip().split(',')

        # Check if the line has the required number of fields (name, age, email, salary)
        if len(parts) != 4:
            raise ValueError(f"Line has missing or extra fields: {line}")
        
        # Extract individual fields
        name, age, email, salary = parts
        
        # Validate that age is a valid integer
        if not age.isdigit():
            raise ValueError(f"Invalid age format: {age} in line: {line}")
        
        # Validate that salary is a valid float
        try:
            salary = float(salary)
        except ValueError:
            raise ValueError(f"Invalid salary format: {salary} in line: {line}")

        # Here, you can add more processing logic if needed, e.g., validate the email format, etc.

        # If no errors, return a dictionary with the processed data
        return {
            "name": name,
            "age": int(age),
            "email": email,
            "salary": salary
        }
    
    except ValueError as e:
        # Log any formatting issues or exceptions
        logging.error(e)
        print(f"Error processing line: {e}")
        return None

# Function to read and process the file
def process_file(filename):
    try:
        with open(filename, 'r') as file:
            for line_num, line in enumerate(file, start=1):
                print(f"Processing line {line_num}: {line.strip()}")
                result = process_line(line)
                if result:
                    print(f"Processed Data: {result}")
                else:
                    print(f"Line {line_num} could not be processed.")
    
    except FileNotFoundError as e:
        logging.error(e)
        print(f"Error: File not found - {filename}")

# Example Usage
if __name__ == "__main__":
    filename = 'pandas.txt' 
    process_file(filename)


Processing line 1: Sandeep,20,sandy@gmail.com,1111
Processed Data: {'name': 'Sandeep', 'age': 20, 'email': 'sandy@gmail.com', 'salary': 1111.0}
Processing line 2: Sandeep Kumar,20,sandeep@gmail.com,1234
Processed Data: {'name': 'Sandeep Kumar', 'age': 20, 'email': 'sandeep@gmail.com', 'salary': 1234.0}
Processing line 3: Random Person,12,theirname@gmail.com,0000
Processed Data: {'name': 'Random Person', 'age': 12, 'email': 'theirname@gmail.com', 'salary': 0.0}


In [9]:
#Question 3

import os
import logging

# Configure logging
logging.basicConfig(filename='directory_size.log', level=logging.INFO,
                    format='%(asctime)s:%(levelname)s:%(message)s')

# Recursive function to calculate the total size of all files in a directory
def get_directory_size(path):
    total_size = 0
    
    try:
        # List all the items in the directory
        with os.scandir(path) as it:
            for entry in it:
                try:
                    if entry.is_file():
                        # If it's a file, add its size to total_size
                        file_size = os.path.getsize(entry.path)
                        total_size += file_size
                        logging.info(f"File: {entry.path}, Size: {file_size} bytes")
                    elif entry.is_dir(follow_symlinks=False):
                        # If it's a directory, make a recursive call to calculate its size
                        logging.info(f"Entering directory: {entry.path}")
                        dir_size = get_directory_size(entry.path)
                        total_size += dir_size
                except PermissionError as e:
                    logging.error(f"Permission denied: {entry.path} - {e}")
                except FileNotFoundError as e:
                    logging.error(f"File not found: {entry.path} - {e}")
    
    except FileNotFoundError as e:
        logging.error(f"Directory not found: {path} - {e}")
    except PermissionError as e:
        logging.error(f"Permission denied: {path} - {e}")
    
    return total_size

# Main function to handle user input and initiate the directory size calculation
def main():
    try:
        # Get the directory path from the user
        dir_path = input("Enter the path of the directory to calculate its size: ")
        
        # Check if the provided path exists and is a directory
        if not os.path.exists(dir_path):
            raise FileNotFoundError(f"Directory does not exist: {dir_path}")
        if not os.path.isdir(dir_path):
            raise NotADirectoryError(f"The path is not a directory: {dir_path}")
        
        # Call the recursive function to calculate the total size
        total_size = get_directory_size(dir_path)
        
        print(f"\nThe total size of all files in '{dir_path}' is {total_size} bytes.")
        logging.info(f"Total size of '{dir_path}': {total_size} bytes")
    
    except FileNotFoundError as e:
        logging.error(e)
        print(f"Error: {e}")
    except NotADirectoryError as e:
        logging.error(e)
        print(f"Error: {e}")

# Run the main function
if __name__ == "__main__":
    main()


Enter the path of the directory to calculate its size: D:\7th Sem

The total size of all files in 'D:\7th Sem' is 1074958829 bytes.
